GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Blog3",
    "author": "AdamH",
    "url": "https://google.com",
    "likes": 10
}

###
PUT http://localhost:3003/api/blogs/60327a4e3cde561ab34e817e
Content-Type: application/json

{
    "title": "Blog1",
    "author": "AdamH",
    "url": "https://google.com",
    "likes": 50
}